macro(CMAssetsManageSetup CMASSETS_MANAGE_ROOT_PATH)

    message("CMASSETS_MANAGE_ROOT_PATH: " ${CMASSETS_MANAGE_ROOT_PATH})

    set(CMASSETS_MANAGE_ROOT_INCLUDE_PATH    ${CMASSETS_MANAGE_ROOT_PATH}/inc)
    set(CMASSETS_MANAGE_ROOT_SOURCE_PATH     ${CMASSETS_MANAGE_ROOT_PATH}/src)

    include_directories(${CMASSETS_MANAGE_ROOT_INCLUDE_PATH})
endmacro()
